name: Build Windows Port
on: [workflow_dispatch]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Build Game Executable
        run: msbuild Game.sln /p:Configuration=Release /p:Platform=Win32 /t:Build

      - name: Upload Native Executable Artifact
        uses: actions/upload-artifact@v4
        with:
          name: residentevil-windows-port
          path: bin/Release/
